version: '3.5'

services:
  mysql:
    image: mysql:8.0
    container_name: zabbix-mysql
    command:
      - --log-bin-trust-function-creators=1
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_ROOT_PASSWORD: root
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    depends_on:
      - mysql
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
    ports:
      - "10051:10051"
    restart: always

  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql
    container_name: zabbix-web
    depends_on:
      - mysql
      - zabbix-server
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "80:8080"
    restart: always
